 const vacature = [{
    id: 1,
    title: "Frontend Developer",
    company: "Google",
    location: "Amsterdam",
    date: "2021-09-01",
    description: "We are looking for a frontend developer to join our team. You will be working on the latest technologies and help us build the next generation of web applications.",
    requirements: [
        "Experience with React",
        "Experience with JavaScript",
        "Experience with HTML/CSS",
        "Experience with Git",
        "Experience with REST APIs"
    ],
    workingHours: "40 hours per week",
    status: "open",
    city: "Amsterdam",
    pay: "€",
    goals: "Developing new user-facing features using React.js",
    responsibilities: "Developing new user-facing features using React.js",
    benefits: "Health insurance, 25 days of paid leave, flexible working hours",
 },{
    id: 2,
    title: "Backend Developer",
    company: "Facebook",
    location: "Berlin",
    date: "2021-09-01",
    description: "We are looking for a backend developer to join our team. You will be working on the latest technologies and help us build the next generation of web applications.",
    requirements: [
        "Experience with Node.js",
        "Experience with Express",
        "Experience with MongoDB",
        "Experience with Git",
        "Experience with REST APIs"
    ],
    workingHours: "40 hours per week",
    status: "open",
    city: "Amsterdam",
    pay: "€",
    goals: "Developing new user-facing features using React.js",
    responsibilities: "Developing new user-facing features using React.js",
    benefits: "Health insurance, 25 days of paid leave, flexible working hours",
 },
 {
    id: 3,
    title: "Backend Developer",
    company: "Facebook",
    location: "Berlin",
    date: "2021-09-01",
    description: "We are looking for a backend developer to join our team. You will be working on the latest technologies and help us build the next generation of web applications.",
    requirements: [
        "Experience with Node.js",
        "Experience with Express",
        "Experience with MongoDB",
        "Experience with Git",
        "Experience with REST APIs"
    ],
    workingHours: "40 hours per week",
    status: "open",
    city: "Amsterdam",
    pay: "€",
    goals: "Developing new user-facing features using React.js",
    responsibilities: "Developing new user-facing features using React.js",
    benefits: "Health insurance, 25 days of paid leave, flexible working hours",
 },
 {
    id: 4,
    title: "Frontend Developer",
    company: "Facebook",
    location: "Berlin",
    date: "2021-09-01",
    description: "We are looking for a backend developer to join our team. You will be working on the latest technologies and help us build the next generation of web applications.",
    requirements: [
        "Experience with Node.js",
        "Experience with Express",
        "Experience with MongoDB",
        "Experience with Git",
        "Experience with REST APIs"
    ],
    workingHours: "40 hours per week",
    status: "open",
    city: "Amsterdam",
    pay: "€",
    goals: "Developing new user-facing features using React.js",
    responsibilities: "Developing new user-facing features using React.js",
    benefits: "Health insurance, 25 days of paid leave, flexible working hours",
 }]

 export default vacature